all: common.h graph.h graph.cpp superstring.cpp
	g++ -Wall -Wextra -O2 -std=c++11 -o superstring.bin superstring.cpp graph.cpp

debug: common.h graph.h graph.cpp superstring.cpp
	g++ -Wall -Wextra -O2 -g -std=c++11 -o superstring.bin superstring.cpp graph.cpp
